name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 触发条件，当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build and Push Docker Image
        run: |
          docker build -t sannysmile/hello-github-action:latest .
          docker push sannysmile/hello-github-action:latest
